-- ============================================================
-- QUESTION 3 - PART 1: CREATE login_audit TABLE
-- Security Login Monitoring System
-- ============================================================
-- This table stores all login attempts (both successful and failed)
-- ============================================================

CREATE TABLE login_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR2(20) NOT NULL CHECK (status IN ('SUCCESS', 'FAILED')),
    ip_address VARCHAR2(50),
    device_info VARCHAR2(200),
    CONSTRAINT chk_status CHECK (status IN ('SUCCESS', 'FAILED'))
);

-- Create indexes for better query performance
CREATE INDEX idx_login_audit_username_time ON login_audit(username, attempt_time);
CREATE INDEX idx_login_audit_status ON login_audit(status);

-- Add comments to table and columns
COMMENT ON TABLE login_audit IS 'Stores all login attempts for auditing and security monitoring';
COMMENT ON COLUMN login_audit.audit_id IS 'Primary key, auto-generated unique identifier';
COMMENT ON COLUMN login_audit.username IS 'Username who attempted to login';
COMMENT ON COLUMN login_audit.attempt_time IS 'Timestamp when the login attempt occurred';
COMMENT ON COLUMN login_audit.status IS 'Login attempt status: SUCCESS or FAILED';
COMMENT ON COLUMN login_audit.ip_address IS 'IP address from which the login attempt was made';
COMMENT ON COLUMN login_audit.device_info IS 'Device or browser information (optional)';

