-- ============================================================
-- QUESTION 3 - PART 2: CREATE security_alerts TABLE
-- Security Login Monitoring System
-- ============================================================
-- This table stores security alerts when users exceed failed login attempts
-- ============================================================

CREATE TABLE security_alerts (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    failed_attempts NUMBER NOT NULL,
    alert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    alert_message VARCHAR2(500) NOT NULL,
    contact_email VARCHAR2(200),
    resolved CHAR(1) DEFAULT 'N' CHECK (resolved IN ('Y', 'N'))
);

-- Create indexes for better query performance
CREATE INDEX idx_security_alerts_username ON security_alerts(username);
CREATE INDEX idx_security_alerts_time ON security_alerts(alert_time);
CREATE INDEX idx_security_alerts_resolved ON security_alerts(resolved);

-- Add comments to table and columns
COMMENT ON TABLE security_alerts IS 'Stores security alerts triggered by multiple failed login attempts';
COMMENT ON COLUMN security_alerts.alert_id IS 'Primary key, auto-generated unique identifier';
COMMENT ON COLUMN security_alerts.username IS 'Username that triggered the security alert';
COMMENT ON COLUMN security_alerts.failed_attempts IS 'Number of failed login attempts that triggered this alert';
COMMENT ON COLUMN security_alerts.alert_time IS 'Timestamp when the alert was created';
COMMENT ON COLUMN security_alerts.alert_message IS 'Detailed message describing the security alert';
COMMENT ON COLUMN security_alerts.contact_email IS 'Email address to notify about this alert';
COMMENT ON COLUMN security_alerts.resolved IS 'Status: Y if resolved, N if still active';

