-- ============================================================
-- QUESTION 4 - PART 1: CREATE patients TABLE
-- Hospital Management Package with Bulk Processing
-- ============================================================
-- This table stores patient information
-- ============================================================

CREATE TABLE patients (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_name VARCHAR2(100) NOT NULL,
    age NUMBER NOT NULL CHECK (age > 0 AND age <= 150),
    gender VARCHAR2(10) NOT NULL CHECK (gender IN ('M', 'F', 'Male', 'Female', 'Other')),
    admitted_status VARCHAR2(10) DEFAULT 'NO' NOT NULL CHECK (admitted_status IN ('YES', 'NO', 'Y', 'N')),
    admission_date DATE,
    discharge_date DATE,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_gender CHECK (gender IN ('M', 'F', 'Male', 'Female', 'Other')),
    CONSTRAINT chk_admitted CHECK (admitted_status IN ('YES', 'NO', 'Y', 'N'))
);

-- Create indexes for better query performance
CREATE INDEX idx_patients_name ON patients(patient_name);
CREATE INDEX idx_patients_admitted ON patients(admitted_status);
CREATE INDEX idx_patients_admission_date ON patients(admission_date);

-- Add comments to table and columns
COMMENT ON TABLE patients IS 'Stores patient information for hospital management system';
COMMENT ON COLUMN patients.patient_id IS 'Primary key, auto-generated unique identifier';
COMMENT ON COLUMN patients.patient_name IS 'Full name of the patient';
COMMENT ON COLUMN patients.age IS 'Age of the patient (must be between 1 and 150)';
COMMENT ON COLUMN patients.gender IS 'Gender: M, F, Male, Female, or Other';
COMMENT ON COLUMN patients.admitted_status IS 'Admission status: YES/NO or Y/N';
COMMENT ON COLUMN patients.admission_date IS 'Date when patient was admitted';
COMMENT ON COLUMN patients.discharge_date IS 'Date when patient was discharged';
COMMENT ON COLUMN patients.created_date IS 'Timestamp when record was created';

