-- ============================================================
-- QUESTION 4 - PART 2: CREATE doctors TABLE
-- Hospital Management Package with Bulk Processing
-- ============================================================
-- This table stores doctor information
-- ============================================================

CREATE TABLE doctors (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_name VARCHAR2(100) NOT NULL,
    specialty VARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(20),
    email VARCHAR2(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX idx_doctors_name ON doctors(doctor_name);
CREATE INDEX idx_doctors_specialty ON doctors(specialty);

-- Add comments to table and columns
COMMENT ON TABLE doctors IS 'Stores doctor information for hospital management system';
COMMENT ON COLUMN doctors.doctor_id IS 'Primary key, auto-generated unique identifier';
COMMENT ON COLUMN doctors.doctor_name IS 'Full name of the doctor';
COMMENT ON COLUMN doctors.specialty IS 'Medical specialty of the doctor';
COMMENT ON COLUMN doctors.phone_number IS 'Contact phone number';
COMMENT ON COLUMN doctors.email IS 'Contact email address';
COMMENT ON COLUMN doctors.created_date IS 'Timestamp when record was created';

